# Generated by Django 2.1.5 on 2019-02-11 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alka', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=35)),
                ('city', models.CharField(max_length=15)),
                ('zip_code', models.CharField(max_length=5)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alka.CustomerInfo')),
            ],
        ),
        migrations.CreateModel(
            name='DepositInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('bottle_type', models.CharField(max_length=25)),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alka.CustomerInfo')),
            ],
        ),
    ]
