# Generated by Django 2.1.5 on 2019-02-11 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alka', '0002_deliveryaddress_depositinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='city',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='street',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='zip_code',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.DeleteModel(
            name='DeliveryAddress',
        ),
    ]
