# Generated by Django 2.1.5 on 2019-02-11 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alka', '0003_auto_20190211_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=35)),
                ('city', models.CharField(blank=True, max_length=15)),
                ('zip_code', models.CharField(blank=True, max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='customerinfo',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customerinfo',
            name='street',
        ),
        migrations.RemoveField(
            model_name='customerinfo',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alka.CustomerInfo'),
        ),
    ]
