# Generated by Django 2.1.5 on 2019-02-11 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alka', '0005_auto_20190211_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositinfo',
            name='bottle_type',
            field=models.IntegerField(choices=[(1, '3 gallon plastic'), (2, '3 gallon plastic w spout'), (3, '3 gallon glass'), (4, '5 gallon plastic'), (5, '5 gallon plastic w spout'), (6, '5 gallon glass'), (7, '5 gallon glass w spout')], default=(1, '3 gallon plastic')),
        ),
    ]
