# Generated by Django 2.1.5 on 2019-02-12 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alka', '0007_auto_20190211_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
