# Generated by Django 2.1.5 on 2019-02-12 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alka', '0010_deliveryaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='customer_id',
        ),
        migrations.DeleteModel(
            name='DeliveryAddress',
        ),
    ]
