# Generated by Django 2.1.5 on 2019-02-12 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alka', '0012_deliveryaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryaddress',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
